[package]
name = "roux_test"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
roux = "2.2.12"
tokio = { version = "1.0", features = ["full"] }

[patch.crates-io]
roux = {path = "/home/lurchfresser/Desktop/coding/crypto/roux"}
